"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Home;
const head_1 = __importDefault(require("next/head"));
const image_1 = __importDefault(require("next/image"));
const google_1 = require("next/font/google");
const Home_module_css_1 = __importDefault(require("@/styles/Home.module.css"));
const geistSans = (0, google_1.Geist)({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = (0, google_1.Geist_Mono)({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
function Home() {
    return (<>
      <head_1.default>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </head_1.default>
      <div className={`${Home_module_css_1.default.page} ${geistSans.variable} ${geistMono.variable}`}>
        <main className={Home_module_css_1.default.main}>
          <image_1.default className={Home_module_css_1.default.logo} src="/next.svg" alt="Next.js logo" width={100} height={20} priority/>
          <div className={Home_module_css_1.default.intro}>
            <h1>To get started, edit the index.tsx file.</h1>
            <p>
              Looking for a starting point or more instructions? Head over to{" "}
              <a href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                Templates
              </a>{" "}
              or the{" "}
              <a href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                Learning
              </a>{" "}
              center.
            </p>
          </div>
          <div className={Home_module_css_1.default.ctas}>
            <a className={Home_module_css_1.default.primary} href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
              <image_1.default className={Home_module_css_1.default.logo} src="/vercel.svg" alt="Vercel logomark" width={16} height={16}/>
              Deploy Now
            </a>
            <a className={Home_module_css_1.default.secondary} href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
              Documentation
            </a>
          </div>
        </main>
      </div>
    </>);
}
//# sourceMappingURL=index.js.map